 [{ 'Sr No': '1',
    Bank: 'BOI',
    'Feeder Branch': 'BOI UDUMALPETTAI',
    'ATM ID': 'CCB8061',
    LOCATION:
     'NO:35,MADURAI ROAD, OPP TO NEW POLICE STATION, DHARAPURAM -638656',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '00:00',
    'Status of Loading': 'NO EOD NO LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance 100': '0',
    'ATM counter details dispense counter 100': '0',
    'ATM counter details divert count 100': '0',
    'ATM counter details remaining counter 100': '0',
    'ATM  Details Physical cash from Cassettes 100': '0',
    'ATM  Details Physical total Cash from Purge Bin 100': '0',
    'ATM  Details Physical total Remaining Cash 100': '0',
    'ATM Return Cash to Vault or Bank cash from Cassettes 100': '0',
    'ATM Return Cash to Vault or Bank seal no 100': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin 100': '0',
    'ATM Repl Details Amount Replenished 100': '0',
    'ATM Repl Details seal no 100': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns 100': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM 100': '0',
    'Switch Counter Opening Balance 100': '0',
    'Switch Counter Dispense as per Switch 100': '0',
    'Switch Counter Loading 100': '0',
    'Switch Counter Admin increase 100': '0',
    'Switch Counter Admin decrease 100': '0',
    'Switch Counter Admin closing 100': '0',
    'Physical Difference Overage 100': '0',
    'Physical Difference Shortage 100': '0',
    'ATM Unfit Currency 100': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'NO SCHEDULE',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '2',
    Bank: 'BOI',
    'Feeder Branch': 'CBD BELAPUR',
    'ATM ID': 'CRG8015',
    LOCATION: 'AT POST JAMBHIVALI, TALUKA KARJAT,DIST-RAIGAD(OFF SITE)',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '14:33',
    'Status of Loading': 'LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance 100': '124200',
    'ATM counter details dispense counter 100': '5300',
    'ATM counter details divert count 100': '0',
    'ATM counter details remaining counter 100': '118900',
    'ATM  Details Physical cash from Cassettes 100': '118900',
    'ATM  Details Physical total Cash from Purge Bin 100': '0',
    'ATM  Details Physical total Remaining Cash 100': '118900',
    'ATM Return Cash to Vault or Bank cash from Cassettes 100': '0',
    'ATM Return Cash to Vault or Bank seal no 100': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin 100': '0',
    'ATM Repl Details Amount Replenished 100': '100000',
    'ATM Repl Details seal no 100': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns 100': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM 100': '218900',
    'Switch Counter Opening Balance 100': '124200',
    'Switch Counter Dispense as per Switch 100': '5300',
    'Switch Counter Loading 100': '100000',
    'Switch Counter Admin increase 100': '0',
    'Switch Counter Admin decrease 100': '0',
    'Switch Counter Admin closing 100': '218900',
    'Physical Difference Overage 100': '0',
    'Physical Difference Shortage 100': '0',
    'ATM Unfit Currency 100': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'Loading done',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '3',
    Bank: 'BOI',
    'Feeder Branch': 'BHOPAL',
    'ATM ID': 'CBO8052',
    LOCATION: 'SHOP NO. 63 PRIYANKA LAJ MANDIDEEP BHOPAL MP (462046)',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '00:00',
    'Status of Loading': 'NO EOD NO LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance 100': '153300',
    'ATM counter details dispense counter 100': '0',
    'ATM counter details divert count 100': '0',
    'ATM counter details remaining counter 100': '153300',
    'ATM  Details Physical cash from Cassettes 100': '153300',
    'ATM  Details Physical total Cash from Purge Bin 100': '0',
    'ATM  Details Physical total Remaining Cash 100': '153300',
    'ATM Return Cash to Vault or Bank cash from Cassettes 100': '0',
    'ATM Return Cash to Vault or Bank seal no 100': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin 100': '0',
    'ATM Repl Details Amount Replenished 100': '0',
    'ATM Repl Details seal no 100': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns 100': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM 100': '153300',
    'Switch Counter Opening Balance 100': '153300',
    'Switch Counter Dispense as per Switch 100': '0',
    'Switch Counter Loading 100': '0',
    'Switch Counter Admin increase 100': '0',
    'Switch Counter Admin decrease 100': '0',
    'Switch Counter Admin closing 100': '153300',
    'Physical Difference Overage 100': '0',
    'Physical Difference Shortage 100': '0',
    'ATM Unfit Currency 100': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'NO EOD GIVEN BY MSP',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '1',
    Bank: 'BOI',
    'Feeder Branch': 'BOI UDUMALPETTAI',
    'ATM ID': 'CCB8061',
    LOCATION:
     'NO:35,MADURAI ROAD, OPP TO NEW POLICE STATION, DHARAPURAM -638656',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '00:00',
    'Status of Loading': 'NO EOD NO LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance 200': '0',
    'ATM counter details dispense counter 200': '0',
    'ATM counter details divert count 200': '0',
    'ATM counter details remaining counter 200': '0',
    'ATM  Details Physical cash from Cassettes 200': '0',
    'ATM  Details Physical total Cash from Purge Bin 200': '0',
    'ATM  Details Physical total Remaining Cash 200': '0',
    'ATM Return Cash to Vault or Bank cash from Cassettes 200': '0',
    'ATM Return Cash to Vault or Bank seal no 200': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin 200': '0',
    'ATM Repl Details Amount Replenished 200': '0',
    'ATM Repl Details seal no 200': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns 200': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM 200': '0',
    'Switch Counter Opening Balance 200': '0',
    'Switch Counter Dispense as per Switch 200': '0',
    'Switch Counter Loading 200': '0',
    'Switch Counter Admin increase 200': '0',
    'Switch Counter Admin decrease 200': '0',
    'Switch Counter Admin closing 200': '0',
    'Physical Difference Overage 200': '0',
    'Physical Difference Shortage 200': '0',
    'ATM Unfit Currency 200': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'NO SCHEDULE',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '2',
    Bank: 'BOI',
    'Feeder Branch': 'CBD BELAPUR',
    'ATM ID': 'CRG8015',
    LOCATION: 'AT POST JAMBHIVALI, TALUKA KARJAT,DIST-RAIGAD(OFF SITE)',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '14:33',
    'Status of Loading': 'LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance 200': '0',
    'ATM counter details dispense counter 200': '0',
    'ATM counter details divert count 200': '0',
    'ATM counter details remaining counter 200': '0',
    'ATM  Details Physical cash from Cassettes 200': '0',
    'ATM  Details Physical total Cash from Purge Bin 200': '0',
    'ATM  Details Physical total Remaining Cash 200': '0',
    'ATM Return Cash to Vault or Bank cash from Cassettes 200': '0',
    'ATM Return Cash to Vault or Bank seal no 200': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin 200': '0',
    'ATM Repl Details Amount Replenished 200': '0',
    'ATM Repl Details seal no 200': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns 200': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM 200': '0',
    'Switch Counter Opening Balance 200': '0',
    'Switch Counter Dispense as per Switch 200': '0',
    'Switch Counter Loading 200': '0',
    'Switch Counter Admin increase 200': '0',
    'Switch Counter Admin decrease 200': '0',
    'Switch Counter Admin closing 200': '0',
    'Physical Difference Overage 200': '0',
    'Physical Difference Shortage 200': '0',
    'ATM Unfit Currency 200': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'Loading done',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '3',
    Bank: 'BOI',
    'Feeder Branch': 'BHOPAL',
    'ATM ID': 'CBO8052',
    LOCATION: 'SHOP NO. 63 PRIYANKA LAJ MANDIDEEP BHOPAL MP (462046)',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '00:00',
    'Status of Loading': 'NO EOD NO LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance 200': '267600',
    'ATM counter details dispense counter 200': '0',
    'ATM counter details divert count 200': '0',
    'ATM counter details remaining counter 200': '267600',
    'ATM  Details Physical cash from Cassettes 200': '267600',
    'ATM  Details Physical total Cash from Purge Bin 200': '0',
    'ATM  Details Physical total Remaining Cash 200': '267600',
    'ATM Return Cash to Vault or Bank cash from Cassettes 200': '0',
    'ATM Return Cash to Vault or Bank seal no 200': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin 200': '0',
    'ATM Repl Details Amount Replenished 200': '0',
    'ATM Repl Details seal no 200': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns 200': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM 200': '267600',
    'Switch Counter Opening Balance 200': '267600',
    'Switch Counter Dispense as per Switch 200': '0',
    'Switch Counter Loading 200': '0',
    'Switch Counter Admin increase 200': '0',
    'Switch Counter Admin decrease 200': '0',
    'Switch Counter Admin closing 200': '267600',
    'Physical Difference Overage 200': '0',
    'Physical Difference Shortage 200': '0',
    'ATM Unfit Currency 200': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'NO EOD GIVEN BY MSP',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '1',
    Bank: 'BOI',
    'Feeder Branch': 'BOI UDUMALPETTAI',
    'ATM ID': 'CCB8061',
    LOCATION:
     'NO:35,MADURAI ROAD, OPP TO NEW POLICE STATION, DHARAPURAM -638656',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '00:00',
    'Status of Loading': 'NO EOD NO LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance 500': '1248500',
    'ATM counter details dispense counter 500': '0',
    'ATM counter details divert count 500': '0',
    'ATM counter details remaining counter 500': '1248500',
    'ATM  Details Physical cash from Cassettes 500': '1248500',
    'ATM  Details Physical total Cash from Purge Bin 500': '0',
    'ATM  Details Physical total Remaining Cash 500': '1248500',
    'ATM Return Cash to Vault or Bank cash from Cassettes 500': '0',
    'ATM Return Cash to Vault or Bank seal no 500': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin 500': '0',
    'ATM Repl Details Amount Replenished 500': '0',
    'ATM Repl Details seal no 500': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns 500': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM 500': '1248500',
    'Switch Counter Opening Balance 500': '1248500',
    'Switch Counter Dispense as per Switch 500': '0',
    'Switch Counter Loading 500': '0',
    'Switch Counter Admin increase 500': '0',
    'Switch Counter Admin decrease 500': '0',
    'Switch Counter Admin closing 500': '1248500',
    'Physical Difference Overage 500': '0',
    'Physical Difference Shortage 500': '0',
    'ATM Unfit Currency 500': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'NO SCHEDULE',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '2',
    Bank: 'BOI',
    'Feeder Branch': 'CBD BELAPUR',
    'ATM ID': 'CRG8015',
    LOCATION: 'AT POST JAMBHIVALI, TALUKA KARJAT,DIST-RAIGAD(OFF SITE)',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '14:33',
    'Status of Loading': 'LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance 500': '496000',
    'ATM counter details dispense counter 500': '197000',
    'ATM counter details divert count 500': '0',
    'ATM counter details remaining counter 500': '299000',
    'ATM  Details Physical cash from Cassettes 500': '299000',
    'ATM  Details Physical total Cash from Purge Bin 500': '0',
    'ATM  Details Physical total Remaining Cash 500': '299000',
    'ATM Return Cash to Vault or Bank cash from Cassettes 500': '0',
    'ATM Return Cash to Vault or Bank seal no 500': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin 500': '0',
    'ATM Repl Details Amount Replenished 500': '1000000',
    'ATM Repl Details seal no 500': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns 500': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM 500': '1299000',
    'Switch Counter Opening Balance 500': '496000',
    'Switch Counter Dispense as per Switch 500': '197000',
    'Switch Counter Loading 500': '1000000',
    'Switch Counter Admin increase 500': '0',
    'Switch Counter Admin decrease 500': '0',
    'Switch Counter Admin closing 500': '1299000',
    'Physical Difference Overage 500': '0',
    'Physical Difference Shortage 500': '0',
    'ATM Unfit Currency 500': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'Loading done',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '3',
    Bank: 'BOI',
    'Feeder Branch': 'BHOPAL',
    'ATM ID': 'CBO8052',
    LOCATION: 'SHOP NO. 63 PRIYANKA LAJ MANDIDEEP BHOPAL MP (462046)',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '00:00',
    'Status of Loading': 'NO EOD NO LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance 500': '1571500',
    'ATM counter details dispense counter 500': '0',
    'ATM counter details divert count 500': '0',
    'ATM counter details remaining counter 500': '1571500',
    'ATM  Details Physical cash from Cassettes 500': '1571500',
    'ATM  Details Physical total Cash from Purge Bin 500': '0',
    'ATM  Details Physical total Remaining Cash 500': '1571500',
    'ATM Return Cash to Vault or Bank cash from Cassettes 500': '0',
    'ATM Return Cash to Vault or Bank seal no 500': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin 500': '0',
    'ATM Repl Details Amount Replenished 500': '0',
    'ATM Repl Details seal no 500': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns 500': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM 500': '1571500',
    'Switch Counter Opening Balance 500': '1571500',
    'Switch Counter Dispense as per Switch 500': '0',
    'Switch Counter Loading 500': '0',
    'Switch Counter Admin increase 500': '0',
    'Switch Counter Admin decrease 500': '0',
    'Switch Counter Admin closing 500': '1571500',
    'Physical Difference Overage 500': '0',
    'Physical Difference Shortage 500': '0',
    'ATM Unfit Currency 500': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'NO EOD GIVEN BY MSP',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '1',
    Bank: 'BOI',
    'Feeder Branch': 'BOI UDUMALPETTAI',
    'ATM ID': 'CCB8061',
    LOCATION:
     'NO:35,MADURAI ROAD, OPP TO NEW POLICE STATION, DHARAPURAM -638656',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '00:00',
    'Status of Loading': 'NO EOD NO LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance 1000': '0',
    'ATM counter details dispense counter 1000': '0',
    'ATM counter details divert count 1000': '0',
    'ATM counter details remaining counter 1000': '0',
    'ATM  Details Physical cash from Cassettes 1000': '0',
    'ATM  Details Physical total Cash from Purge Bin 1000': '0',
    'ATM  Details Physical total Remaining Cash 1000': '0',
    'ATM Return Cash to Vault or Bank cash from Cassettes 1000': '0',
    'ATM Return Cash to Vault or Bank seal no 1000': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin 1000': '0',
    'ATM Repl Details Amount Replenished 1000': '0',
    'ATM Repl Details seal no 1000': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns 1000': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM 1000': '0',
    'Switch Counter Opening Balance 1000': '0',
    'Switch Counter Dispense as per Switch 1000': '0',
    'Switch Counter Loading 1000': '0',
    'Switch Counter Admin increase 1000': '0',
    'Switch Counter Admin decrease 1000': '0',
    'Switch Counter Admin closing 1000': '0',
    'Physical Difference Overage 1000': '0',
    'Physical Difference Shortage 1000': '0',
    'ATM Unfit Currency 1000': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'NO SCHEDULE',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '2',
    Bank: 'BOI',
    'Feeder Branch': 'CBD BELAPUR',
    'ATM ID': 'CRG8015',
    LOCATION: 'AT POST JAMBHIVALI, TALUKA KARJAT,DIST-RAIGAD(OFF SITE)',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '14:33',
    'Status of Loading': 'LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance 1000': '0',
    'ATM counter details dispense counter 1000': '0',
    'ATM counter details divert count 1000': '0',
    'ATM counter details remaining counter 1000': '0',
    'ATM  Details Physical cash from Cassettes 1000': '0',
    'ATM  Details Physical total Cash from Purge Bin 1000': '0',
    'ATM  Details Physical total Remaining Cash 1000': '0',
    'ATM Return Cash to Vault or Bank cash from Cassettes 1000': '0',
    'ATM Return Cash to Vault or Bank seal no 1000': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin 1000': '0',
    'ATM Repl Details Amount Replenished 1000': '0',
    'ATM Repl Details seal no 1000': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns 1000': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM 1000': '0',
    'Switch Counter Opening Balance 1000': '0',
    'Switch Counter Dispense as per Switch 1000': '0',
    'Switch Counter Loading 1000': '0',
    'Switch Counter Admin increase 1000': '0',
    'Switch Counter Admin decrease 1000': '0',
    'Switch Counter Admin closing 1000': '0',
    'Physical Difference Overage 1000': '0',
    'Physical Difference Shortage 1000': '0',
    'ATM Unfit Currency 1000': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'Loading done',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '3',
    Bank: 'BOI',
    'Feeder Branch': 'BHOPAL',
    'ATM ID': 'CBO8052',
    LOCATION: 'SHOP NO. 63 PRIYANKA LAJ MANDIDEEP BHOPAL MP (462046)',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '00:00',
    'Status of Loading': 'NO EOD NO LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance 1000': '0',
    'ATM counter details dispense counter 1000': '0',
    'ATM counter details divert count 1000': '0',
    'ATM counter details remaining counter 1000': '0',
    'ATM  Details Physical cash from Cassettes 1000': '0',
    'ATM  Details Physical total Cash from Purge Bin 1000': '0',
    'ATM  Details Physical total Remaining Cash 1000': '0',
    'ATM Return Cash to Vault or Bank cash from Cassettes 1000': '0',
    'ATM Return Cash to Vault or Bank seal no 1000': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin 1000': '0',
    'ATM Repl Details Amount Replenished 1000': '0',
    'ATM Repl Details seal no 1000': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns 1000': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM 1000': '0',
    'Switch Counter Opening Balance 1000': '0',
    'Switch Counter Dispense as per Switch 1000': '0',
    'Switch Counter Loading 1000': '0',
    'Switch Counter Admin increase 1000': '0',
    'Switch Counter Admin decrease 1000': '0',
    'Switch Counter Admin closing 1000': '0',
    'Physical Difference Overage 1000': '0',
    'Physical Difference Shortage 1000': '0',
    'ATM Unfit Currency 1000': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'NO EOD GIVEN BY MSP',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '1',
    Bank: 'BOI',
    'Feeder Branch': 'BOI UDUMALPETTAI',
    'ATM ID': 'CCB8061',
    LOCATION:
     'NO:35,MADURAI ROAD, OPP TO NEW POLICE STATION, DHARAPURAM -638656',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '00:00',
    'Status of Loading': 'NO EOD NO LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance 2000': '0',
    'ATM counter details dispense counter 2000': '0',
    'ATM counter details divert count 2000': '0',
    'ATM counter details remaining counter 2000': '0',
    'ATM  Details Physical cash from Cassettes 2000': '0',
    'ATM  Details Physical total Cash from Purge Bin 2000': '0',
    'ATM  Details Physical total Remaining Cash 2000': '0',
    'ATM Return Cash to Vault or Bank cash from Cassettes 2000': '0',
    'ATM Return Cash to Vault or Bank seal no 2000': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin 2000': '0',
    'ATM Repl Details Amount Replenished 2000': '0',
    'ATM Repl Details seal no 2000': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns 2000': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM 2000': '0',
    'Switch Counter Opening Balance 2000': '0',
    'Switch Counter Dispense as per Switch 2000': '0',
    'Switch Counter Loading 2000': '0',
    'Switch Counter Admin increase 2000': '0',
    'Switch Counter Admin decrease 2000': '0',
    'Switch Counter Admin closing 2000': '0',
    'Physical Difference Overage 2000': '0',
    'Physical Difference Shortage 2000': '0',
    'ATM Unfit Currency 2000': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'NO SCHEDULE',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '2',
    Bank: 'BOI',
    'Feeder Branch': 'CBD BELAPUR',
    'ATM ID': 'CRG8015',
    LOCATION: 'AT POST JAMBHIVALI, TALUKA KARJAT,DIST-RAIGAD(OFF SITE)',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '14:33',
    'Status of Loading': 'LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance 2000': '0',
    'ATM counter details dispense counter 2000': '0',
    'ATM counter details divert count 2000': '0',
    'ATM counter details remaining counter 2000': '0',
    'ATM  Details Physical cash from Cassettes 2000': '0',
    'ATM  Details Physical total Cash from Purge Bin 2000': '0',
    'ATM  Details Physical total Remaining Cash 2000': '0',
    'ATM Return Cash to Vault or Bank cash from Cassettes 2000': '0',
    'ATM Return Cash to Vault or Bank seal no 2000': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin 2000': '0',
    'ATM Repl Details Amount Replenished 2000': '0',
    'ATM Repl Details seal no 2000': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns 2000': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM 2000': '0',
    'Switch Counter Opening Balance 2000': '0',
    'Switch Counter Dispense as per Switch 2000': '0',
    'Switch Counter Loading 2000': '0',
    'Switch Counter Admin increase 2000': '0',
    'Switch Counter Admin decrease 2000': '0',
    'Switch Counter Admin closing 2000': '0',
    'Physical Difference Overage 2000': '0',
    'Physical Difference Shortage 2000': '0',
    'ATM Unfit Currency 2000': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'Loading done',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '3',
    Bank: 'BOI',
    'Feeder Branch': 'BHOPAL',
    'ATM ID': 'CBO8052',
    LOCATION: 'SHOP NO. 63 PRIYANKA LAJ MANDIDEEP BHOPAL MP (462046)',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '00:00',
    'Status of Loading': 'NO EOD NO LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance 2000': '0',
    'ATM counter details dispense counter 2000': '0',
    'ATM counter details divert count 2000': '0',
    'ATM counter details remaining counter 2000': '0',
    'ATM  Details Physical cash from Cassettes 2000': '0',
    'ATM  Details Physical total Cash from Purge Bin 2000': '0',
    'ATM  Details Physical total Remaining Cash 2000': '0',
    'ATM Return Cash to Vault or Bank cash from Cassettes 2000': '0',
    'ATM Return Cash to Vault or Bank seal no 2000': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin 2000': '0',
    'ATM Repl Details Amount Replenished 2000': '0',
    'ATM Repl Details seal no 2000': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns 2000': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM 2000': '0',
    'Switch Counter Opening Balance 2000': '0',
    'Switch Counter Dispense as per Switch 2000': '0',
    'Switch Counter Loading 2000': '0',
    'Switch Counter Admin increase 2000': '0',
    'Switch Counter Admin decrease 2000': '0',
    'Switch Counter Admin closing 2000': '0',
    'Physical Difference Overage 2000': '0',
    'Physical Difference Shortage 2000': '0',
    'ATM Unfit Currency 2000': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'NO EOD GIVEN BY MSP',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '1',
    Bank: 'BOI',
    'Feeder Branch': 'BOI UDUMALPETTAI',
    'ATM ID': 'CCB8061',
    LOCATION:
     'NO:35,MADURAI ROAD, OPP TO NEW POLICE STATION, DHARAPURAM -638656',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '00:00',
    'Status of Loading': 'NO EOD NO LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance Total': '1248500',
    'ATM counter details dispense counter Total': '0',
    'ATM counter details divert count Total': '0',
    'ATM counter details remaining counter Total': '1248500',
    'ATM  Details Physical cash from Cassettes Total': '1248500',
    'ATM  Details Physical total Cash from Purge Bin Total': '0',
    'ATM  Details Physical total Remaining Cash Total': '1248500',
    'ATM Return Cash to Vault or Bank cash from Cassettes Total': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin Total': '0',
    'ATM Repl Details Amount Replenished Total': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns Total': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM Total': '1248500',
    'Switch Counter Opening Balance Total': '1248500',
    'Switch Counter Dispense as per Switch Total': '0',
    'Switch Counter Loading Total': '0',
    'Switch Counter Admin increase Total': '0',
    'Switch Counter Admin decrease Total': '0',
    'Switch Counter Admin closing Total': '1248500',
    'Physical Difference Overage Total': '0',
    'Physical Difference Shortage Total': '0',
    'ATM Unfit Currency Total': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'NO SCHEDULE',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '2',
    Bank: 'BOI',
    'Feeder Branch': 'CBD BELAPUR',
    'ATM ID': 'CRG8015',
    LOCATION: 'AT POST JAMBHIVALI, TALUKA KARJAT,DIST-RAIGAD(OFF SITE)',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '14:33',
    'Status of Loading': 'LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance Total': '620200',
    'ATM counter details dispense counter Total': '202300',
    'ATM counter details divert count Total': '0',
    'ATM counter details remaining counter Total': '417900',
    'ATM  Details Physical cash from Cassettes Total': '417900',
    'ATM  Details Physical total Cash from Purge Bin Total': '0',
    'ATM  Details Physical total Remaining Cash Total': '417900',
    'ATM Return Cash to Vault or Bank cash from Cassettes Total': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin Total': '0',
    'ATM Repl Details Amount Replenished Total': '1100000',
    'ATM Returns or Closing Balance Total ATM Cash Returns Total': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM Total': '1517900',
    'Switch Counter Opening Balance Total': '620200',
    'Switch Counter Dispense as per Switch Total': '202300',
    'Switch Counter Loading Total': '1100000',
    'Switch Counter Admin increase Total': '0',
    'Switch Counter Admin decrease Total': '0',
    'Switch Counter Admin closing Total': '1517900',
    'Physical Difference Overage Total': '0',
    'Physical Difference Shortage Total': '0',
    'ATM Unfit Currency Total': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'Loading done',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' },
  { 'Sr No': '3',
    Bank: 'BOI',
    'Feeder Branch': 'BHOPAL',
    'ATM ID': 'CBO8052',
    LOCATION: 'SHOP NO. 63 PRIYANKA LAJ MANDIDEEP BHOPAL MP (462046)',
    Date: '2021-03-01 00:00:00',
    'Eod or Loading Time': '00:00',
    'Status of Loading': 'NO EOD NO LOADING',
    'Last Transaction No': '0',
    CRA: 'SECURE VALUE',
    'Indent No': '0',
    'Bank Ref No': '0',
    'ATM counter details opening balance Total': '1992400',
    'ATM counter details dispense counter Total': '0',
    'ATM counter details divert count Total': '0',
    'ATM counter details remaining counter Total': '1992400',
    'ATM  Details Physical cash from Cassettes Total': '1992400',
    'ATM  Details Physical total Cash from Purge Bin Total': '0',
    'ATM  Details Physical total Remaining Cash Total': '1992400',
    'ATM Return Cash to Vault or Bank cash from Cassettes Total': '0',
    'ATM Return Cash to Vault or Bank Total Cash from Purge Bin Total': '0',
    'ATM Repl Details Amount Replenished Total': '0',
    'ATM Returns or Closing Balance Total ATM Cash Returns Total': '0',
    'ATM Returns or Closing Balance Closing Balance in ATM Total': '1992400',
    'Switch Counter Opening Balance Total': '1992400',
    'Switch Counter Dispense as per Switch Total': '0',
    'Switch Counter Loading Total': '0',
    'Switch Counter Admin increase Total': '0',
    'Switch Counter Admin decrease Total': '0',
    'Switch Counter Admin closing Total': '1992400',
    'Physical Difference Overage Total': '0',
    'Physical Difference Shortage Total': '0',
    'ATM Unfit Currency Total': '0',
    'Status one': 'OK',
    'Status two': 'OK',
    Remarks: 'NO EOD GIVEN BY MSP',
    processName: 'ate',
    clientName: 'test',
    id: 'test1234' } ]
